### PR TITLE
extract NodeStatusTuple inner class

### PR DESCRIPTION
**Pull request by driesdeproost**
Annotation is not processed when on the inner class

Looks related to https://github.com/rzwitserloot/lombok/issues/1684

### CODE REVIEW

**Comment by kerkhofsd** [comment]
Then why did this work before?

**Comment by tgeens** [comment]
I'm using lombok annotations on inner classes all the time ?

**Comment by driesdeproost** [comment]
> Then why did this work before?

It's not that it doesn't work functionally. It's about being able to look into the sources of this project when using it as a dependency in a non-lombok project. The problem is that when someone that is not using lombok in a project and is depending on this package looks into the source of this project, that person will not have the needed lombok packages for its IDE to resolve links. Lombok is nice, but IMO we should not burden users of this package with unresolved lombok dependencies when having a look in the sources.

This issue did not show because we often use lombok in other projects anyway. And when we don't, we probably didn't look into the sources.
 
We could also solve this problem by making the lombok dependency not compileOnly, but compile. So that pulling in transitive dependencies fixes this problem

**Comment by tgeens** [comment]
@driesdeproost fine argument, but does moving the `@Data` annotated inner class to a seperate class actually help ?

**Comment by driesdeproost** [comment]
Yes, the annotation is then processed.
However, thinking about it, I think it's better to just include the dependency. This way we don't have to remember that this behaviour exists and we can happily continue to annotate inner classes.
WDYT?

**Comment by tgeens** [comment]
lombok should not be a transitive dependency, that leads to bigger issues

**Review by tgeens — APPROVED** [review]
Although the rationale is wonky, moving this inner class out is fine by me.

**Comment by driesdeproost** [comment]
In the mean time I've noticed that there were more occurences. Best to fix all of it at one point.
This is not really a priority right now. I'll close this PR and make a ticket referring here, so we can take on this nuisance later.

**Pull request closed without merging**
